from . import ve_declaracion_iva
from . import ve_dashboard_iva
from . import ve_sancion_iva
from . import res_partner
from . import res_company
from . import account_move
from . import ve_wh_iva
from . import ve_wh_iva_prov
from . import ve_seniat_retencion
from . import ve_declarado_mensual
from . import ve_conciliacion
from . import ve_comprobante_inbox
from . import res_config_settings
from . import whatsapp_hook
from . import ve_conecta_carga_ventas
from . import ve_conecta_carga_compras
